<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXDBwoyq\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXDBwoyq/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXDBwoyq.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXDBwoyq\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXDBwoyq\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XDBwoyq',
    'container.build_id' => '3a97257d',
    'container.build_time' => 1578855328,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXDBwoyq');
